name: Build with PyInstaller

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --name "DanMuScreen" --onefile --icon=icons.ico src/main.py --noconsole --add-data="icons.ico:."

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v3
        with:
          name: DanMuScreen-Windows
          path: dist/DanMuScreen.exe
    
  # Job for building on macOS
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install Pillow  # Install Pillow for icon conversion

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --name "DanMuScreen" --onefile --icon=icons.ico src/main.py --noconsole --add-data="icons.ico:."

      - name: Compress macOS Application
        run: zip -r DanMuScreen-macOS.zip dist/DanMuScreen.app
        
      - name: Upload macOS Executable
        uses: actions/upload-artifact@v3
        with:
          name: DanMuScreen-macOS
          path: DanMuScreen-macOS.zip

  # Job for building on Linux
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --name "DanMuScreen" --onefile --icon=icons.ico src/main.py --noconsole --add-data="icons.ico:."

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v3
        with:
          name: DanMuScreen-Linux
          path: dist/DanMuScreen

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]  # Wait for all build jobs to complete
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: DanMuScreen-Windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: DanMuScreen-Linux

      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: DanMuScreen-macOS
      
      - name: List Directory
        run: |
          tree -L 2

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
              DanMuScreen
              DanMuScreen.exe
              DanMuScreen.zip